#! /bin/sh

sxhkd &
dunst &
picom &
$HOME/.config/polybar/launch.sh
pamixer --set-volume 0

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           60

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 0
